DROP TABLE IF EXISTS MY_PRODUCT;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS CATEGORY;

CREATE TABLE CATEGORY (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255)
);
	
CREATE TABLE PRODUCT (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255),
	features VARCHAR(255),
	description VARCHAR(255),
	price DOUBLE,
	quantity INT,
	color VARCHAR(255),
	category_id INT NOT NULL,
	FOREIGN KEY (`category_id`) REFERENCES `CATEGORY` (`id`)
);